version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: doctor_clinic_db

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - medical_pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dr_admin -d clinic_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  medical_pgdata: